<template>
  <div class="home-page">
    <Banner />
    <section ref="recommendSection" class="section section-featured"><div class="page-container"><header class="section-head"><div><p class="section-kicker">EDITOR'S PICK &middot; 01</p><h2 class="section-title">本周推荐</h2><p class="section-note">从实用性出发，挑出值得放进学习计划的资料。</p></div><router-link to="/resources" class="section-link">浏览资源库 <span>&rarr;</span></router-link></header><div v-if="recommendResources.length" class="resource-grid"><ResourceCard v-for="item in recommendResources" :key="item.id" :resource="item" /></div><EmptyState v-else-if="!recommendLoading" text="推荐资料正在整理中" /><div v-else class="resource-grid"><div v-for="i in 4" :key="i" class="skeleton-card"><n-skeleton :height="180" /><div class="skeleton-body"><n-skeleton text :repeat="2" /></div></div></div></div></section>
    <section ref="hotSection" class="section section-hot"><div class="page-container"><header class="section-head"><div><p class="section-kicker">MOST READ &middot; 02</p><h2 class="section-title">大家都在看</h2><p class="section-note">近期被频繁翻阅与下载的热门资料。</p></div><router-link to="/resources" class="section-link">查看全部 <span>&rarr;</span></router-link></header><div v-if="hotResources.length" class="resource-grid"><ResourceCard v-for="item in hotResources.slice(0, 4)" :key="item.id" :resource="item" /></div><EmptyState v-else-if="!hotLoading" text="热门资料正在汇总中" /><div v-else class="resource-grid"><div v-for="i in 4" :key="i" class="skeleton-card"><n-skeleton :height="180" /><div class="skeleton-body"><n-skeleton text :repeat="2" /></div></div></div></div></section>
    <section ref="latestSection" class="section section-latest"><div class="page-container"><header class="section-head"><div><p class="section-kicker">NEWLY ADDED &middot; 03</p><h2 class="section-title">刚刚入库</h2><p class="section-note">持续更新，让每一份新资料都能被及时找到。</p></div><router-link to="/resources" class="section-link">按时间浏览 <span>&rarr;</span></router-link></header><div v-if="latestResources.length" class="resource-grid"><ResourceCard v-for="item in latestResources.slice(0, 4)" :key="item.id" :resource="item" /></div><EmptyState v-else-if="!latestLoading" text="新资料正在路上" /><div v-else class="resource-grid"><div v-for="i in 4" :key="i" class="skeleton-card"><n-skeleton :height="180" /><div class="skeleton-body"><n-skeleton text :repeat="2" /></div></div></div></div></section>
  </div>
</template>
<script setup>
import { ref, onMounted, onBeforeUnmount } from 'vue'
import Banner from '@/components/front/Banner.vue'; import ResourceCard from '@/components/front/ResourceCard.vue'; import EmptyState from '@/components/front/EmptyState.vue'; import { getRecommendResources, getHotResources, getLatestResources } from '@/api/resource'
const recommendResources=ref([]),hotResources=ref([]),latestResources=ref([]),recommendLoading=ref(true),hotLoading=ref(true),latestLoading=ref(true),recommendSection=ref(null),hotSection=ref(null),latestSection=ref(null); let observer=null
function observeSection(el){if(el&&observer)observer.observe(el)}
onMounted(async()=>{observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('section-visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -32px 0px'});[recommendSection,hotSection,latestSection].forEach(section=>observeSection(section.value));try{const[recRes,hotRes,latestRes]=await Promise.all([getRecommendResources(4),getHotResources(4),getLatestResources(4)]);recommendResources.value=recRes.data||[];hotResources.value=hotRes.data||[];latestResources.value=latestRes.data||[]}catch{}finally{recommendLoading.value=false;hotLoading.value=false;latestLoading.value=false}})
onBeforeUnmount(()=>{if(observer)observer.disconnect()})
</script>
<style scoped>
.section{padding:84px 0 90px;opacity:0;transform:translateY(18px);transition:opacity .55s ease,transform .55s ease}.section-visible{opacity:1;transform:translateY(0)}.section-featured{background:var(--bg)}.section-hot{position:relative;background:#e9f0eb}.section-hot::before{content:'';position:absolute;inset:0;opacity:.22;background-image:linear-gradient(90deg,rgba(15,109,112,.1) 1px,transparent 1px),linear-gradient(rgba(15,109,112,.1) 1px,transparent 1px);background-size:28px 28px;pointer-events:none}.section-hot .page-container{position:relative}.section-latest{background:var(--bg)}.section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:30px;padding-bottom:19px;border-bottom:1px solid var(--border)}.section-kicker{margin:0 0 9px;color:#a2743d;font:600 10px/1.2 'PingFang SC','Microsoft YaHei',sans-serif;letter-spacing:.16em}.section-note{margin:9px 0 0;color:var(--text-secondary);font:13px/1.6 'PingFang SC','Microsoft YaHei',sans-serif}.section-link{display:inline-flex;align-items:center;gap:8px;flex-shrink:0;padding-bottom:3px;color:#4e746f;font:13px/1.3 'PingFang SC','Microsoft YaHei',sans-serif}.section-link span{font:20px/1 Georgia,serif;transition:transform var(--transition-fast)}.section-link:hover span{transform:translateX(4px)}.resource-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.skeleton-card{min-height:305px;overflow:hidden;background:var(--paper);border:1px solid var(--border-light)}.skeleton-body{padding:18px}@media(max-width:980px){.resource-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.section{padding:54px 0 58px}.section-head{align-items:flex-start;flex-direction:column;gap:15px;margin-bottom:20px}.section-link{padding:0}.resource-grid{gap:11px}.section-note{max-width:280px;font-size:12px}}
</style>
