<template>
  <div v-if="categories.length" class="category-nav"><section v-for="(section, idx) in categories" :key="section.id" class="category-section"><div class="category-index">{{ String(idx + 1).padStart(2, '0') }}</div><div class="category-content"><div class="category-header"><span class="category-main"><span class="category-icon" :style="{ color: iconColor(idx) }">{{ section.name.charAt(0) }}</span><span>{{ section.name }}</span></span><router-link :to="{ path: '/resources', query: { categoryId: section.id } }" class="category-more">查看全部 <span>&rarr;</span></router-link></div><div v-if="section.children && section.children.length" class="category-children"><router-link v-for="child in section.children" :key="child.id" :to="{ path: '/resources', query: { categoryId: child.id } }" class="category-child">{{ child.name }}</router-link></div></div></section></div>
  <div v-else-if="loading" class="category-loading"><n-skeleton text :repeat="3" /></div>
</template>
<script setup>
import { ref, onMounted } from 'vue'; import { getCategoryTree } from '@/api/category'
const categories = ref([]); const loading = ref(true); const iconColors = ['#0f6d70','#b36e26','#597b55','#9c5d45','#596d84']; function iconColor(idx) { return iconColors[idx % iconColors.length] }
onMounted(async () => { try { const res = await getCategoryTree(); categories.value = res.data || [] } catch {} finally { loading.value = false } })
</script>
<style scoped>
.category-nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));border-top:1px solid var(--border);border-left:1px solid var(--border)}.category-section{display:grid;grid-template-columns:58px 1fr;min-height:155px;background:rgba(255,253,248,.72);border-right:1px solid var(--border);border-bottom:1px solid var(--border);transition:background var(--transition)}.category-section:hover{background:var(--paper)}.category-index{padding:23px 0 0 17px;color:#b4a98f;font:italic 22px/1 Georgia,serif}.category-content{padding:21px 22px 20px 0}.category-header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding-bottom:14px;border-bottom:1px solid var(--border-light)}.category-main{display:flex;align-items:center;gap:10px;color:var(--ink);font-size:18px;font-weight:700}.category-icon{display:grid;place-items:center;width:28px;height:28px;border:1px solid currentColor;border-radius:50%;font:600 13px/1 'PingFang SC','Microsoft YaHei',sans-serif}.category-more{display:inline-flex;align-items:center;gap:5px;flex-shrink:0;color:#66807c;font:11px/1 'PingFang SC','Microsoft YaHei',sans-serif}.category-more span{font:17px/1 Georgia,serif;transition:transform var(--transition-fast)}.category-more:hover span{transform:translateX(4px)}.category-children{display:flex;flex-wrap:wrap;gap:8px 15px;padding-top:15px}.category-child{position:relative;color:#667875;font:13px/1.4 'PingFang SC','Microsoft YaHei',sans-serif}.category-child::before{content:'\00b7';margin-right:4px;color:var(--accent)}.category-child:hover{color:var(--primary-dark)}.category-loading{padding:20px}@media(max-width:768px){.category-nav{grid-template-columns:1fr}.category-section{min-height:130px;grid-template-columns:48px 1fr}.category-index{padding-left:14px;font-size:18px}.category-content{padding:17px 16px 16px 0}.category-main{font-size:16px}}
</style>
